<?php
return [
    'icons' => [
        '<i class="icon-scissors3"></i>' => '',
        '<i class="icon-mobile3"></i>' => '',
        '<i class="icon-desktop"></i>' => '',
        '<i class="icon-documents2"></i>' => '',
        '<i class="icon-laptop3"></i>' => '',
        '<i class="icon-tablet3"></i>' => '',
        '<i class="icon-phone3"></i>' => '',
        '<i class="icon-document2"></i>' => '',
        '<i class="icon-search2"></i>' => '',
        '<i class="icon-clipboard3"></i>' => '',
        '<i class="icon-newspaper2"></i>' => '',
        '<i class="icon-notebook"></i>' => '',
        '<i class="icon-book-open"></i>' => '',
        '<i class="icon-browser2"></i>' => '',
        '<i class="icon-calendar3"></i>' => '',
        '<i class="icon-presentation"></i>' => '',
        '<i class="icon-picture"></i>' => '',
        '<i class="icon-pictures"></i>' => '',
        '<i class="icon-video2"></i>' => '',
        '<i class="icon-camera3"></i>' => '',
        '<i class="icon-printer2"></i>' => '',
        '<i class="icon-toolbox"></i>' => '',
        '<i class="icon-briefcase3"></i>' => '',
        '<i class="icon-wallet2"></i>' => '',
        '<i class="icon-gift2"></i>' => '',
        '<i class="icon-bargraph"></i>' => '',
        '<i class="icon-grid2"></i>' => '',
        '<i class="icon-expand"></i>' => '',
        '<i class="icon-focus"></i>' => '',
        '<i class="icon-edit2"></i>' => '',
        '<i class="icon-adjustments"></i>' => '',
        '<i class="icon-ribbon"></i>' => '',
        '<i class="icon-hourglass"></i>' => '',
        '<i class="icon-lock3"></i>' => '',
        '<i class="icon-megaphone2"></i>' => '',
        '<i class="icon-shield3"></i>' => '',
        '<i class="icon-trophy3"></i>' => '',
        '<i class="icon-flag3"></i>' => '',
        '<i class="icon-map3"></i>' => '',
        '<i class="icon-puzzle"></i>' => '',
        '<i class="icon-basket"></i>' => '',
        '<i class="icon-envelope"></i>' => '',
        '<i class="icon-streetsign"></i>' => '',
        '<i class="icon-telescope"></i>' => '',
        '<i class="icon-gears"></i>' => '',
        '<i class="icon-key3"></i>' => '',
        '<i class="icon-paperclip"></i>' => '',
        '<i class="icon-attachment3"></i>' => '',
        '<i class="icon-pricetags"></i>' => '',
        '<i class="icon-lightbulb"></i>' => '',
        '<i class="icon-layers2"></i>' => '',
        '<i class="icon-pencil3"></i>' => '',
        '<i class="icon-tools2"></i>' => '',
        '<i class="icon-tools-2"></i>' => '',
        '<i class="icon-paintbrush"></i>' => '',
        '<i class="icon-magnifying-glass2"></i>' => '',
        '<i class="icon-circle-compass"></i>' => '',
        '<i class="icon-linegraph"></i>' => '',
        '<i class="icon-mic3"></i>' => '',
        '<i class="icon-strategy"></i>' => '',
        '<i class="icon-beaker"></i>' => '',
        '<i class="icon-caution"></i>' => '',
        '<i class="icon-recycle"></i>' => '',
        '<i class="icon-anchor"></i>' => '',
        '<i class="icon-profile-male"></i>' => '',
        '<i class="icon-profile-female"></i>' => '',
        '<i class="icon-bike"></i>' => '',
        '<i class="icon-wine"></i>' => '',
        '<i class="icon-hotairballoon"></i>' => '',
        '<i class="icon-globe2"></i>' => '',
        '<i class="icon-genius"></i>' => '',
        '<i class="icon-map-pin"></i>' => '',
        '<i class="icon-chat2"></i>' => '',
        '<i class="icon-heart3"></i>' => '',
        '<i class="icon-cloud3"></i>' => '',
        '<i class="icon-upload4"></i>' => '',
        '<i class="icon-download4"></i>' => '',
        '<i class="icon-target2"></i>' => '',
        '<i class="icon-hazardous"></i>' => '',
        '<i class="icon-piechart"></i>' => '',
        '<i class="icon-speedometer"></i>' => '',
        '<i class="icon-global"></i>' => '',
        '<i class="icon-compass3"></i>' => '',
        '<i class="icon-lifesaver"></i>' => '',
        '<i class="icon-clock3"></i>' => '',
        '<i class="icon-aperture"></i>' => '',
        '<i class="icon-quote2"></i>' => '',
        '<i class="icon-scope"></i>' => '',
        '<i class="icon-alarmclock"></i>' => '',
        '<i class="icon-refresh"></i>' => '',
        '<i class="icon-happy3"></i>' => '',
        '<i class="icon-sad3></i>' => '',
        '<i class="icon-facebook3"></i>' => '',
        '<i class="icon-twitter3"></i>' => '',
        '<i class="icon-googleplus"></i>' => '',
        '<i class="icon-rss3"></i>' => '',
        '<i class="icon-tumblr3></i>' => '',
        '<i class="icon-linkedin3"></i>' => '',
        '<i class="icon-dribbble3"></i>' => '',
        '<i class="icon-vk2"></i>' => '',
        '<i class="icon-instagram2"></i>' => '',
        '<i class="icon-whatsapp"></i>' => '',
        '<i class="icon-telegram"></i>' => '',
        '<i class="icon-skype2"></i>' => '',
        '<i class="icon-svg"></i>' => '',
        '<i class="icon-youtube2"></i>' => '',
        ],
    'data' => [
        '<i class="icon-scissors3"></i>' => ['data-content' => '<i class="icon-scissors3"></i>'],
        '<i class="icon-mobile3"></i>' => ['data-content' => '<i class="icon-mobile3"></i>'],
        '<i class="icon-desktop"></i>' => ['data-content' => '<i class="icon-desktop"></i>'],
        '<i class="icon-documents2"></i>' => ['data-content' => '<i class="icon-documents2"></i>'],
        '<i class="icon-laptop3"></i>' => ['data-content' => '<i class="icon-laptop3"></i>'],
        '<i class="icon-tablet3"></i>' => ['data-content' => '<i class="icon-mobile3"></i>'],
        '<i class="icon-phone3"></i>' => ['data-content' => '<i class="icon-phone3"></i>'],
        '<i class="icon-document2"></i>' => ['data-content' => '<i class="icon-document2"></i>'],
        '<i class="icon-search2"></i>' => ['data-content' => '<i class="icon-search2"></i>'],
        '<i class="icon-clipboard3"></i>' => ['data-content' => '<i class="icon-clipboard3"></i>'],
        '<i class="icon-newspaper2"></i>' => ['data-content' => '<i class="icon-newspaper2"></i>'],
        '<i class="icon-notebook"></i>' => ['data-content' => '<i class="icon-notebook"></i>'],
        '<i class="icon-book-open"></i>' => ['data-content' => '<i class="icon-book-open"></i>'],
        '<i class="icon-browser2"></i>' => ['data-content' => '<i class="icon-browser2"></i>'],
        '<i class="icon-calendar3"></i>' => ['data-content' => '<i class="icon-calendar3"></i>'],
        '<i class="icon-presentation"></i>' => ['data-content' => '<i class="icon-presentation"></i>'],
        '<i class="icon-picture"></i>' => ['data-content' => '<i class="icon-picture"></i>'],
        '<i class="icon-pictures"></i>' => ['data-content' => '<i class="icon-pictures"></i>'],
        '<i class="icon-video2"></i>' => ['data-content' => '<i class="icon-video2"></i>'],
        '<i class="icon-camera3"></i>' => ['data-content' => '<i class="icon-camera3"></i>'],
        '<i class="icon-printer2"></i>' => ['data-content' => '<i class="icon-printer2"></i>'],
        '<i class="icon-toolbox"></i>' => ['data-content' => '<i class="icon-toolbox"></i>'],
        '<i class="icon-briefcase3"></i>' => ['data-content' => '<i class="icon-briefcase3"></i>'],
        '<i class="icon-wallet2"></i>' => ['data-content' => '<i class="icon-wallet2"></i>'],
        '<i class="icon-gift2"></i>' => ['data-content' => '<i class="icon-gift2"></i>'],
        '<i class="icon-bargraph"></i>' => ['data-content' => '<i class="icon-bargraph"></i>'],
        '<i class="icon-grid2"></i>' => ['data-content' => '<i class="icon-grid2"></i>'],
        '<i class="icon-expand"></i>' => ['data-content' => '<i class="icon-expand"></i>'],
        '<i class="icon-focus"></i>' => ['data-content' => '<i class="icon-focus"></i>'],
        '<i class="icon-edit2"></i>' => ['data-content' => '<i class="icon-edit2"></i>'],
        '<i class="icon-adjustments"></i>' => ['data-content' => '<i class="icon-adjustments"></i>'],
        '<i class="icon-ribbon"></i>' => ['data-content' => '<i class="icon-ribbon"></i>'],
        '<i class="icon-hourglass"></i>' => ['data-content' => '<i class="icon-hourglass"></i>'],
        '<i class="icon-lock3"></i>' => ['data-content' => '<i class="icon-lock3"></i>'],
        '<i class="icon-megaphone2"></i>' => ['data-content' => '<i class="icon-megaphone2"></i>'],
        '<i class="icon-shield3"></i>' => ['data-content' => '<i class="icon-shield3"></i>'],
        '<i class="icon-trophy3"></i>' => ['data-content' => '<i class="icon-trophy3"></i>'],
        '<i class="icon-flag3"></i>' => ['data-content' => '<i class="icon-flag3"></i>'],
        '<i class="icon-map3"></i>' => ['data-content' => '<i class="icon-map3"></i>'],
        '<i class="icon-puzzle"></i>' => ['data-content' => '<i class="icon-puzzle"></i>'],
        '<i class="icon-basket"></i>' => ['data-content' => '<i class="icon-basket"></i>'],
        '<i class="icon-envelope"></i>' => ['data-content' => '<i class="icon-envelope"></i>'],
        '<i class="icon-streetsign"></i>' => ['data-content' => '<i class="icon-streetsign"></i>'],
        '<i class="icon-telescope"></i>' => ['data-content' => '<i class="icon-telescope"></i>'],
        '<i class="icon-gears"></i>' => ['data-content' => '<i class="icon-gears"></i>'],
        '<i class="icon-key3"></i>' => ['data-content' => '<i class="icon-key3"></i>'],
        '<i class="icon-paperclip"></i>' => ['data-content' => '<i class="icon-paperclip"></i>'],
        '<i class="icon-attachment3"></i>' => ['data-content' => '<i class="icon-attachment3"></i>'],
        '<i class="icon-pricetags"></i>' => ['data-content' => '<i class="icon-pricetags"></i>'],
        '<i class="icon-lightbulb"></i>' => ['data-content' => '<i class="icon-lightbulb"></i>'],
        '<i class="icon-layers2"></i>' => ['data-content' => '<i class="icon-layers2"></i>'],
        '<i class="icon-pencil3"></i>' => ['data-content' => '<i class="icon-pencil3"></i>'],
        '<i class="icon-tools2"></i>' => ['data-content' => '<i class="icon-tools2"></i>'],
        '<i class="icon-tools-2"></i>' => ['data-content' => '<i class="icon-tools-2"></i>'],
        '<i class="icon-paintbrush"></i>' => ['data-content' => '<i class="icon-paintbrush"></i>'],
        '<i class="icon-magnifying-glass2"></i>' => ['data-content' => '<i class="icon-magnifying-glass2"></i>'],
        '<i class="icon-circle-compass"></i>' => ['data-content' => '<i class="icon-circle-compass"></i>'],
        '<i class="icon-linegraph"></i>' => ['data-content' => '<i class="icon-linegraph"></i>'],
        '<i class="icon-mic3"></i>' => ['data-content' => '<i class="icon-mic3"></i>'],
        '<i class="icon-strategy"></i>' => ['data-content' => '<i class="icon-strategy"></i>'],
        '<i class="icon-beaker"></i>' => ['data-content' => '<i class="icon-beaker"></i>'],
        '<i class="icon-caution"></i>' => ['data-content' => '<i class="icon-caution"></i>'],
        '<i class="icon-recycle"></i>' => ['data-content' => '<i class="icon-recycle"></i>'],
        '<i class="icon-anchor"></i>' => ['data-content' => '<i class="icon-anchor"></i>'],
        '<i class="icon-profile-male"></i>' => ['data-content' => '<i class="icon-profile-male"></i>'],
        '<i class="icon-profile-female"></i>' => ['data-content' => '<i class="icon-profile-female"></i>'],
        '<i class="icon-bike"></i>' => ['data-content' => '<i class="icon-bike"></i>'],
        '<i class="icon-wine"></i>' => ['data-content' => '<i class="icon-wine"></i>'],
        '<i class="icon-hotairballoon"></i>' => ['data-content' => '<i class="icon-hotairballoon"></i>'],
        '<i class="icon-globe2"></i>' => ['data-content' => '<i class="icon-globe2"></i>'],
        '<i class="icon-genius"></i>' => ['data-content' => '<i class="icon-genius"></i>'],
        '<i class="icon-map-pin"></i>' => ['data-content' => '<i class="icon-map-pin"></i>'],
        '<i class="icon-chat2"></i>' => ['data-content' => '<i class="icon-chat2"></i>'],
        '<i class="icon-heart3"></i>' => ['data-content' => '<i class="icon-heart3"></i>'],
        '<i class="icon-cloud3"></i>' => ['data-content' => '<i class="icon-cloud3"></i>'],
        '<i class="icon-upload4"></i>' => ['data-content' => '<i class="icon-upload4"></i>'],
        '<i class="icon-download4"></i>' => ['data-content' => '<i class="icon-download4"></i>'],
        '<i class="icon-target2"></i>' => ['data-content' => '<i class="icon-target2"></i>'],
        '<i class="icon-hazardous"></i>' => ['data-content' => '<i class="icon-hazardous"></i>'],
        '<i class="icon-piechart"></i>' => ['data-content' => '<i class="icon-piechart"></i>'],
        '<i class="icon-speedometer"></i>' => ['data-content' => '<i class="icon-speedometer"></i>'],
        '<i class="icon-global"></i>' => ['data-content' => '<i class="icon-global"></i>'],
        '<i class="icon-compass3"></i>' => ['data-content' => '<i class="icon-compass3"></i>'],
        '<i class="icon-lifesaver"></i>' => ['data-content' => '<i class="icon-lifesaver"></i>'],
        '<i class="icon-clock3"></i>' => ['data-content' => '<i class="icon-clock3"></i>'],
        '<i class="icon-aperture"></i>' => ['data-content' => '<i class="icon-aperture"></i>'],
        '<i class="icon-quote2"></i>' => ['data-content' => '<i class="icon-quote2"></i>'],
        '<i class="icon-scope"></i>' => ['data-content' => '<i class="icon-scope"></i>'],
        '<i class="icon-alarmclock"></i>' => ['data-content' => '<i class="icon-alarmclock"></i>'],
        '<i class="icon-refresh"></i>' => ['data-content' => '<i class="icon-refresh"></i>'],
        '<i class="icon-happy3"></i>' => ['data-content' => '<i class="icon-happy3"></i>'],
        '<i class="icon-sad3"></i>' => ['data-content' => '<i class="icon-sad3"></i>'],
        '<i class="icon-facebook3"></i>' => ['data-content' => '<i class="icon-facebook3"></i>'],
        '<i class="icon-twitter3"></i>' => ['data-content' => '<i class="icon-twitter3"></i>'],
        '<i class="icon-googleplus"></i>' => ['data-content' => '<i class="icon-googleplus"></i>'],
        '<i class="icon-rss3"></i>' => ['data-content' => '<i class="icon-rss3"></i>'],
        '<i class="icon-tumblr3"></i>' => ['data-content' => '<i class="icon-tumblr3"></i>'],
        '<i class="icon-linkedin3"></i>' => ['data-content' => '<i class="icon-linkedin3"></i>'],
        '<i class="icon-dribbble3"></i>' => ['data-content' => '<i class="icon-dribbble3"></i>'],
        '<i class="icon-vk2"></i>' => ['data-content' => '<i class="icon-vk2"></i>'],
        '<i class="icon-instagram2"></i>' => ['data-content' => '<i class="icon-instagram2"></i>'],
        '<i class="icon-whatsapp"></i>' => ['data-content' => '<i class="icon-whatsapp"></i>'],
        '<i class="icon-telegram"></i>' => ['data-content' => '<i class="icon-telegram"></i>'],
        '<i class="icon-skype2"></i>' => ['data-content' => '<i class="icon-skype2"></i>'],
        '<i class="icon-svg"></i>' => ['data-content' => '<i class="icon-svg"></i>'],
        '<i class="icon-youtube2"></i>' => ['data-content' => '<i class="icon-youtube2"></i>'],
    ],


];